### ISSUE TITLE
Treat all operations

### ISSUE THREAD

**Issue by CreativeBulma** [mathias-meyer/composer-package-updater#1]
Hi,

great plugin.
One correction: you should loop into all packages instead of only getting the first one.
```php
$event_operations = $event->getOperations();
foreach($event_operations as $event_operation) {
}
```
regards,

**Comment by werbfred** [comment]
Hello CreativeBulma,

Thank you for your feedback. I would not expect to handle more operations than the one from the PackageEvent itself. Tests I perofrmed show that every package that gets installed/updated/uninstalled will trigger that function.

Underlying question is: What is being found in the other operations? If there is the whole list of other packages that will be updated as well? Handling that situtation would be of the responbility of the package that will get forwarded the event.

Mathias

**Comment by werbfred** [comment]
Can I close issue?

**Comment by CreativeBulma** [comment]
Hi,

sorry about the delay. You're right: "Handling that situtation would be of the responbility of the package that will get forwarded the event."

so you can close the issue.
