### ISSUE TITLE
Dispatch other events than 'PackageEvent'

### ISSUE THREAD

**Issue by cavasinf** [mathias-meyer/composer-package-updater#5]
**I know with your current code, it is not possible BUT,**

With your knowledge and workarounds, it is possible to trigger other events to bundles that is not related to one specific package (install, update , ...) ?

By that I mean, can I do a `composer install` that trigger nested events in bundles ?

**Note**: 
Related to the doc, `composer install` trigger an `Composer\Script\Event` [See class here](https://github.com/composer/composer/blob/master/src/Composer/Script/Event.php).
In that class there is no way to get the package/bundle who can respond to that event (which is normal).
In that case, your `trust` parameter cannot work.

## Use case: 
- I've multiple bundles with multiple entities
- One of my bundle is my "main" bundle.
- I've multiple "migrations" in each bundles.

## What I want:
I wan't to copy all `Migrations` from my bundles into the main folder `/Migrations`

## Example:

1. FooBundle:
- Version20190108212000.php
- Version20190116220535.php

2. BarBundle:
- Version20190115214707.php
- Version20190416092453.php

3. `/src/Migrations`:
- Version20190114214508.php

Content of folder 1 & 2 will be cp in folder 3

============

If for you, it's possible to do something, I'll try to make a piece of code and a PR.

**Comment by werbfred** [comment]
Hello,

I somehow see what you intend to do, but not 100% sure.

Can you please provide more details of your workflow of files you want to copy from your bundles into the `/src/Migrations` destination.

What prevents you from handling the **post-package-install** or **post-package-update** events forwarded to each of your packages to perform the copy the files to your desired destination ?

Maybe should we agree on the **bundle** term. What would be the difference between a **package** and a **bundle** ?

**Comment by cavasinf** [comment]
Hi, 
the problem is that *post-package-install* or *post-package-update* is only triggered when the package is not installed or need to be updated. And not when `composer install` is called.

But with your answer, you pointed me something important: 
if I add/change/delete a file in my bundle, I'll automaticaly update the version of my bundle.
So **post-package-update** will handle that!

I'll try to work with that for now, thx for the anwser (and your code).

**Comment by werbfred** [comment]
You are always welcome :)
